version: '3'
services:
  nest-app:
    build: .
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
    links:
      - mongo
    depends_on:
      - mongo
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=demoiner
      - MONGO_INITDB_ROOT_PASSWORD=mypass
    ports:
      - "27017:27017"
    volumes:
      - mongo-db:/data/db
volumes:
  mongo-db:
